export const QUERY_KEYS = {
  PROFILE: ["profile"],
  PLAN_DETAILS: ["plan_details"],
  RESI_COUNTRY: ["resi_country"],
  PRODUCTS: ["products"],
  PRICING: ["pricing"],
  ORDERS: ["orders"],
  POOL_TYPES: ["pool_types"],
  USER_CONFIGS: ["user_configs"],
  TRANSACTIONS: ["transactions"],
  PLANS: ["plans"],
  USER_PLAN: ["user_plan"],
  RESI_PACKAGES: ["resi_packages"],
  PURCHASE_OVERVIEW: ["purchase_overview"],
  DATA_USAGE: ["data_usage"],
};
