import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactQueryClientProvider } from "@/providers";
import { ToastContainer } from "react-toastify";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Proxy app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-main-bg">
        <ToastContainer position="bottom-center" autoClose={5000} />
        <Suspense>
          <ReactQueryClientProvider>{children}</ReactQueryClientProvider>
        </Suspense>
      </body>
    </html>
  );
}
